from sqlalchemy import (
    Column,
    String,
    Float,
    Integer,
    Boolean,
    DateTime,
    Text,
    ForeignKey,
    Enum as SAEnum,
)
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.orm import declarative_base, relationship
from datetime import datetime
import uuid
import enum

Base = declarative_base()


# ─── Enums ───────────────────────────────────────────────────────────────────

class SignalDirection(str, enum.Enum):
    LONG = "long"
    SHORT = "short"


class SignalStatus(str, enum.Enum):
    PENDING = "pending"
    TAKEN = "taken"
    SKIPPED = "skipped"
    EXPIRED = "expired"


class PositionStatus(str, enum.Enum):
    OPEN = "open"
    CLOSED = "closed"


class TradeResult(str, enum.Enum):
    WIN = "win"
    LOSS = "loss"
    BREAKEVEN = "breakeven"


class BotRunStatus(str, enum.Enum):
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"


# ─── Models ───────────────���──────────────────────────────────────────────────

class Strategy(Base):
    """Trading strategies (e.g., zone_wide_us, zone_verystrong_se)."""
    __tablename__ = "strategies"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    name = Column(String(100), unique=True, nullable=False)
    description = Column(Text, nullable=True)
    version = Column(String(20), default="1.0")
    config = Column(JSONB, nullable=True)  # Strategy parameters as JSON
    is_active = Column(Boolean, default=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Relationships
    signals = relationship("Signal", back_populates="strategy")
    bot_runs = relationship("BotRun", back_populates="strategy")


class Signal(Base):
    """Trading signals generated by strategies/bots."""
    __tablename__ = "signals"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    strategy_id = Column(UUID(as_uuid=True), ForeignKey("strategies.id"), nullable=False)
    ticker = Column(String(20), nullable=False)
    direction = Column(SAEnum(SignalDirection), nullable=False)
    entry_price = Column(Float, nullable=True)
    stop_loss = Column(Float, nullable=True)
    take_profit = Column(Float, nullable=True)
    confidence = Column(Float, nullable=True)  # 0.0 - 1.0
    status = Column(SAEnum(SignalStatus), default=SignalStatus.PENDING)
    metadata_ = Column("metadata", JSONB, nullable=True)  # Extra signal data
    signal_time = Column(DateTime, default=datetime.utcnow)
    expires_at = Column(DateTime, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)

    # Relationships
    strategy = relationship("Strategy", back_populates="signals")
    position = relationship("Position", back_populates="signal", uselist=False)


class Position(Base):
    """Open/closed positions - when a signal is taken."""
    __tablename__ = "positions"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    signal_id = Column(UUID(as_uuid=True), ForeignKey("signals.id"), nullable=True)
    ticker = Column(String(20), nullable=False)
    direction = Column(SAEnum(SignalDirection), nullable=False)
    entry_price = Column(Float, nullable=False)
    stop_loss = Column(Float, nullable=True)
    take_profit = Column(Float, nullable=True)
    quantity = Column(Float, nullable=True)
    status = Column(SAEnum(PositionStatus), default=PositionStatus.OPEN)
    notes = Column(Text, nullable=True)
    opened_at = Column(DateTime, default=datetime.utcnow)
    closed_at = Column(DateTime, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Relationships
    signal = relationship("Signal", back_populates="position")
    trade = relationship("Trade", back_populates="position", uselist=False)


class Trade(Base):
    """Completed trades with P&L calculation."""
    __tablename__ = "trades"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    position_id = Column(UUID(as_uuid=True), ForeignKey("positions.id"), nullable=False)
    ticker = Column(String(20), nullable=False)
    direction = Column(SAEnum(SignalDirection), nullable=False)
    entry_price = Column(Float, nullable=False)
    exit_price = Column(Float, nullable=False)
    quantity = Column(Float, nullable=True)
    pnl = Column(Float, nullable=True)  # Absolute P&L
    pnl_percent = Column(Float, nullable=True)  # Percentage P&L
    result = Column(SAEnum(TradeResult), nullable=False)
    fees = Column(Float, default=0.0)
    notes = Column(Text, nullable=True)
    opened_at = Column(DateTime, nullable=False)
    closed_at = Column(DateTime, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow)

    # Relationships
    position = relationship("Position", back_populates="trade")


class MarketSnapshot(Base):
    """Market data snapshots for reference (no live data)."""
    __tablename__ = "market_snapshots"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    ticker = Column(String(20), nullable=False)
    price = Column(Float, nullable=False)
    volume = Column(Float, nullable=True)
    rsi = Column(Float, nullable=True)
    atr = Column(Float, nullable=True)
    metadata_ = Column("metadata", JSONB, nullable=True)
    snapshot_time = Column(DateTime, default=datetime.utcnow)
    created_at = Column(DateTime, default=datetime.utcnow)


class BotRun(Base):
    """Log of bot/strategy execution runs."""
    __tablename__ = "bot_runs"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    strategy_id = Column(UUID(as_uuid=True), ForeignKey("strategies.id"), nullable=False)
    status = Column(SAEnum(BotRunStatus), default=BotRunStatus.RUNNING)
    signals_generated = Column(Integer, default=0)
    tickers_scanned = Column(Integer, default=0)
    error_message = Column(Text, nullable=True)
    metadata_ = Column("metadata", JSONB, nullable=True)
    started_at = Column(DateTime, default=datetime.utcnow)
    completed_at = Column(DateTime, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)

    # Relationships
    strategy = relationship("Strategy", back_populates="bot_runs")
